import { integer, jsonb, timestamp, varchar } from "drizzle-orm/pg-core";

/**
 * Spreadable column groups so the universal entity metadata required by
 * docs/data/02_DATA_MODEL.md cannot be forgotten on a new table.
 *
 * Column names are emitted as snake_case automatically via
 * `casing: "snake_case"` in drizzle.config.ts / createDbClient.
 */

/** Prefixed ULIDs are generated by the application, never by the database. */
export const ID_LENGTH = 40;

export const idColumn = () => varchar("id", { length: ID_LENGTH }).primaryKey();

/** FK/actor reference to another prefixed ID. */
export const idRef = (name: string) => varchar(name, { length: ID_LENGTH });

export const auditColumns = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  createdBy: varchar("created_by", { length: ID_LENGTH }),
  updatedBy: varchar("updated_by", { length: ID_LENGTH }),
  /** Optimistic locking — every update must compare-and-swap on this. */
  version: integer("version").notNull().default(1),
};

/**
 * Soft delete is the default for business entities. Operational tables
 * (sessions, idempotency_keys) deliberately omit this and expire instead.
 */
export const softDeleteColumns = {
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  deletedBy: varchar("deleted_by", { length: ID_LENGTH }),
};

export const metadataColumn = {
  metadata: jsonb("metadata").notNull().default({}),
};
