// @ts-check
// Frontend layer (Next.js apps — apps/web, apps/admin, apps/landing, ...)
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import next from "@next/eslint-plugin-next";
import { baseConfig } from "./base.js";

export const nextjsConfig = tseslint.config(
  ...baseConfig,
  {
    // Auto-generated by Next.js on every build — not ours to lint.
    ignores: ["next-env.d.ts"],
  },
  {
    plugins: {
      react,
      "react-hooks": reactHooks,
      "@next/next": next,
    },
    languageOptions: {
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    settings: {
      react: { version: "detect" },
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...next.configs.recommended.rules,
      ...next.configs["core-web-vitals"].rules,
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
    },
  },
);

export default nextjsConfig;
